// 문제 추가
var createExam = function() {
	str =  '<br><br>';
	str += '<div class="d5">                                                           ';
	str += '	<div class="d4"></div>                                                 ';
	str += '	<div class="d6">                                                       ';
	str += '		<label for="sel1" class="sel1"> 문제를 입력해주세요. </label> <br> <input       ';
	str += '			type="text" name="queCont" class="form-control que" /> <br>   ';
	str += '		<label for="sel2"> 보기를 입력해주세요. </label>                   ';
	str += '		<div class="anw">                                                  ';
	str += '			<div class="overlay"></div>                                                  ';
	str += '			<input type="text" name="ansCont" class="form-control radi"   ';
	str += '				placeholder="보기1"> <input type="checkbox" name="que_answer" ';
	str += '				value="1" class="chk" />                             ';
	str += '		</div>                                                             ';
	str += '		<div class="anw">                                                  ';
	str += '			<div class="overlay"></div>                                                  ';
	str += '			<input type="text" name="ansCont" class="form-control radi"   ';
	str += '				placeholder="보기2"> <input type="checkbox" name="queAnswer" ';
	str += '				value="2" class="chk" />                                               ';
	str += '		</div>                                                             ';
	str += '		<div class="anw">                                                  ';
	str += '			<div class="overlay"></div>                                                  ';
	str += '			<input type="text" name="ansCont" class="form-control radi"   ';
	str += '				placeholder="보기3"> <input type="checkbox" name="queAnswer" ';
	str += '				value="3" class="chk" />                                               ';
	str += '		</div>                                                             ';
	str += '		<div class="anw">                                                  ';
	str += '			<div class="overlay"></div>                                                  ';
	str += '			<input type="text" name="ansCont" class="form-control radi"   ';
	str += '				placeholder="보기4"> <input type="checkbox" name="queAnswer" ';
	str += '				value="4" class="chk" />                                               ';
	str += '		</div>                                                             ';
	str += '		<br> <label for="sel3"> 문제 해설을 입력해주세요. </label>         ';
	str += '		<div class="anw">                                                  ';
	str += '			<textarea class="form-control" rows="5" class="comment"           ';
	str += '				name="queExplain" style="resize: none"></textarea>                             ';
	str += '		</div>                                                             ';
	str += '	</div>                                                                 ';
	str += '</div>';

	$('#d2').append(str);
};