// 문제 추가
var createExam = function() {
	str =  '<br><br>';
	str += '<div class="d5">                                                                                                           ';
	str += '	<div class="d4"></div>                                                                                                 ';
	str += '	<div class="d6">                                                                                                       ';
	str += '		<label for="sel1" class="sel1"> 문제를 입력해주세요. </label> <br>                                                          ';
	str += '		<input type="text" name="queContList" class="form-control que" /><br>                                              ';
	str += '		<label for="sel1" class="sel1"> 배점을 입력해주세요. </label> <br>                                                          ';
	str += '		<input type="text" name="queScoreList" class="form-control que" /><br>                                             ';
	str += '		                                                                                                                   ';
	str += '		<label for="sel2"> 보기를 입력해주세요. </label>                                                                            ';
	str += '		<div class="anw">                                                                                                  ';
	str += '			<div class="overlay"></div>                                                                                    ';
	str += '			<input type="text" name="ansContList" class="form-control radi" placeholder="보기1">                             ';
	str += '			<input type="checkbox" name="queAnswerList" value="1" class="chk" />                                           ';
	str += '		</div>                                                                                                             ';
	str += '		<div class="anw">                                                                                                  ';
	str += '			<div class="overlay"></div>                                                                                    ';
	str += '			<input type="text" name="ansContList" class="form-control radi" placeholder="보기2">                             ';
	str += '			<input type="checkbox" name="queAnswerList" value="2" class="chk" />                                           ';
	str += '		</div>                                                                                                             ';
	str += '		<div class="anw">                                                                                                  ';
	str += '			<div class="overlay"></div>                                                                                    ';
	str += '			<input type="text" name="ansContList" class="form-control radi" placeholder="보기3">                             ';
	str += '			<input type="checkbox" name="queAnswerList" value="3" class="chk" />                                           ';
	str += '		</div>                                                                                                             ';
	str += '		<div class="anw">                                                                                                  ';
	str += '			<div class="overlay"></div>                                                                                    ';
	str += '			<input type="text" name="ansContList" class="form-control radi" placeholder="보기4">                             ';
	str += '			<input type="checkbox" name="queAnswerList" value="4" class="chk" />                                           ';
	str += '		</div>                                                                                                             ';
	str += '		<br> <label for="sel3"> 문제 해설을 입력해주세요. </label>                                                                    ';
	str += '		<div class="anw">                                                                                                  ';
	str += '			<textarea class="form-control" rows="5" class="comment" name="queExplainList" style="resize: none"></textarea> ';
	str += '		</div>                                                                                                             ';
	str += '	</div>                                                                                                                 ';
	str += '</div>';
	
	$('#d2').append(str);
};